# Generated by Django 3.1.2 on 2020-10-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201021_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
        ),
    ]
