# Generated by Django 3.1.2 on 2020-10-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201021_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenting_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
