# Generated by Django 3.1.2 on 2020-10-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201021_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='selling_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selling_user', to='auctions.user'),
            preserve_default=False,
        ),
    ]
