# Generated by Django 3.1.2 on 2020-10-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_selling_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='closed_listing',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='closed_listing', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
