# Generated by Django 3.1.2 on 2020-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201027_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_active',
            field=models.BooleanField(default=False),
        ),
    ]
