# Generated by Django 3.1.2 on 2020-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow_follow_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_active',
            field=models.BooleanField(default=False),
        ),
    ]
