# Generated by Django 3.1.2 on 2020-10-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201028_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Connection',
        ),
    ]
