# Generated by Django 3.1.2 on 2020-10-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201029_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='follow_active',
            new_name='connection_is_active',
        ),
    ]
